# Generated by Django 5.1.2 on 2025-02-16 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_notification_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
    ]
