# Generated by Django 5.1.2 on 2025-02-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_notification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='slug',
            field=models.SlugField(blank=True, max_length=20),
        ),
    ]
