# Generated by Django 5.0 on 2024-10-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_rename_transaction_price_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='proof_of_payment',
            field=models.FileField(blank=True, upload_to='images/proof_of_payment'),
        ),
    ]
