# Generated by Django 5.0 on 2024-10-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_transaction_proof_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
