# Generated by Django 5.0 on 2024-10-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='userBalance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
    ]
