# Generated by Django 5.0 on 2024-10-31 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_alter_withdrawalaccount_user_withdrawal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawalaccount',
            old_name='BankName',
            new_name='account_name',
        ),
        migrations.RenameField(
            model_name='withdrawalaccount',
            old_name='acount_name',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='withdrawalaccount',
            old_name='acount_number',
            new_name='bank_name',
        ),
    ]
