# Generated by Django 5.0 on 2025-01-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('account_holder_name', models.CharField(max_length=500)),
                ('currency', models.CharField(help_text='Accepted currency for this account. E.g.: USD, EUR, NGN', max_length=10)),
            ],
            options={
                'verbose_name': 'BankDetail',
                'verbose_name_plural': 'BankDetails',
            },
        ),
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crytopName', models.CharField(max_length=255)),
                ('walletAddress', models.CharField(max_length=255)),
                ('cryptoSymbol', models.CharField(help_text='E.g.: BTC, ETH, USDT', max_length=10)),
            ],
            options={
                'verbose_name': 'CryptoWallet',
                'verbose_name_plural': 'CryptoWallets',
            },
        ),
    ]
