# Generated by Django 5.0 on 2025-01-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheltradeAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionName', models.CharField(max_length=255)),
                ('charge', models.PositiveIntegerField(help_text='Percentage(%) per transaction')),
            ],
            options={
                'verbose_name': 'Transaction Charge',
                'verbose_name_plural': 'Transaction Charges',
            },
        ),
    ]
