# Generated by Django 5.1.2 on 2025-02-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheltradeAdmin', '0004_rename_crytopname_cryptowallet_cryptoname'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptowallet',
            name='minimumDeposit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum deposit amount. E.g: 0.00100000 ETH', max_digits=10, null=True),
        ),
    ]
