# Generated by Django 5.1.2 on 2025-02-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheltradeAdmin', '0005_cryptowallet_minimumdeposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptowallet',
            name='minimumDeposit',
            field=models.DecimalField(blank=True, decimal_places=100, help_text='Minimum deposit amount. E.g: 0.00100000 ETH', max_digits=150, null=True),
        ),
    ]
