# Generated by Django 5.0 on 2024-10-18 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(blank=True, choices=[('amazon', 'Amazon'), ('itunes', 'iTunes'), ('google-play', 'Google Play'), ('steam', 'Steam'), ('other', 'Other')], default='other', max_length=50)),
                ('other_card_type', models.CharField(blank=True, max_length=100, null=True)),
                ('card_number', models.CharField(max_length=100)),
                ('card_pin', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_image', models.ImageField(upload_to='gift_cards/')),
                ('status', models.CharField(choices=[('on the market', 'On the Market'), ('sold', 'Sold')], default='on the market', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
