# Generated by Django 5.0 on 2024-10-31 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftcard',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='giftcard',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='giftcard',
            name='card_image',
        ),
        migrations.RemoveField(
            model_name='giftcard',
            name='other_card_type',
        ),
        migrations.RemoveField(
            model_name='giftcard',
            name='user',
        ),
        migrations.AddField(
            model_name='giftcard',
            name='card_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='condition',
            field=models.CharField(blank=True, help_text='Condition of the gift card (new, used, partially used)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='escrow_status',
            field=models.CharField(choices=[('held', 'Held'), ('released', 'Released')], default='held', max_length=10),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='restrictions',
            field=models.TextField(blank=True, help_text='Any specific terms or restrictions', null=True),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='gift_cards/'),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='card_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='card_pin',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='card_type',
            field=models.CharField(help_text='Brand/retailer name e.g., Amazon, Steam', max_length=50),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('listed', 'Listed for Sale')], default='pending', max_length=10),
        ),
    ]
