# Generated by Django 5.0 on 2024-10-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0003_buygiftcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='escrow_status',
            field=models.CharField(choices=[('held', 'Held'), ('released', 'Released'), ('refunded', 'Refunded')], default='held', max_length=10),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('listed', 'Listed for Sale'), ('Sold', 'Sold')], default='pending', max_length=10),
        ),
    ]
