# Generated by Django 5.0 on 2024-11-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0004_alter_giftcard_escrow_status_alter_giftcard_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcard',
            name='escrow_status',
        ),
        migrations.AddField(
            model_name='buygiftcard',
            name='escrow_status',
            field=models.CharField(choices=[('held', 'Held'), ('released', 'Released'), ('refunded', 'Refunded')], default='held', max_length=10),
        ),
    ]
