# Generated by Django 5.0 on 2024-11-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0005_remove_giftcard_escrow_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('listed', 'Listed for Sale'), ('Sold', 'Sold')], default='listed', max_length=10),
        ),
    ]
