# Generated by Django 5.0 on 2025-01-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('invalid', 'Invalid'), ('listed', 'Listed for Sale'), ('sold', 'Sold')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/gift_cards/'),
        ),
    ]
