# Generated by Django 5.0 on 2025-01-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0002_alter_giftcard_status_alter_giftcard_uploaded_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='status',
            field=models.CharField(choices=[('Pending Verification', 'pending'), ('Invalid', 'invalid'), ('Listed for Sale', 'listed'), ('Sold', 'sold')], db_index=True, default='Pending Verification', max_length=50),
        ),
    ]
