# Generated by Django 5.0 on 2025-01-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0003_alter_giftcard_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('invalid', 'Invalid'), ('listed', 'Listed for Sale'), ('sold', 'Sold')], db_index=True, default='pending', max_length=50),
        ),
    ]
