# Generated by Django 5.1.2 on 2025-02-04 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='adress',
            new_name='address',
        ),
    ]
